version: '3'


services:
    db:
      container_name: postgress_account
      image: postgres:15.2
      restart: always
      ports:
         - ${DB_PORT}:${DB_PORT}
      volumes:
         - ./db_backup:/var/lib/postgresql/data/
      expose:
         - ${DB_PORT}
      environment:
         POSTGRES_USER: ${DB_USER}
         POSTGRES_PASSWORD: ${DB_PASS}
         POSTGRES_DB: ${DB_NAME}


    rabbitMq:
      container_name: account_rabitmq
      image: rabbitmq:3-management-alpine
      ports:
         - 5672:5672
         - 15672:15672
