version: '3'

services:
    db:
      container_name: postgress_account
      image: postgres:15.2
      restart: always
      ports:
         - ${DB_PORT}:${DB_PORT}
      volumes:
         - ./db_backup:/var/lib/postgresql/data/
      expose:
         - ${DB_PORT}
      environment:
         POSTGRES_USER: ${DB_USER}
         POSTGRES_PASSWORD: ${DB_PASS}
         POSTGRES_DB: ${DB_NAME}


    db_test:
      container_name: postgress_account_test
      image: postgres:15.2
      restart: always
      ports:
         - ${DB_PORT_TEST}:${DB_PORT_TEST}
      expose:
         - ${DB_PORT_TEST}
      environment:
         POSTGRES_USER: ${DB_USER_TEST}
         POSTGRES_PASSWORD: ${DB_PASS_TEST}
         POSTGRES_DB: ${DB_NAME_TEST}


    rabbitMq:
      container_name: account_rabitmq
      image: rabbitmq:3-management-alpine
      ports:
         - 5672:5672
         - 15672:15672
